services:
  - type: web
    name: rogue-lycan-server
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start

  - type: static
    name: rogue-lycan-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
